name: Test

on:
  push:
    branches:
      - luci-20.029
    paths:
      - '.github/workflows/test.yml'
      - 'luasrc/model/cbi/*'
      - 'luasrc/controller/*'
      - 'po/zh-cn/*'
      - 'root/**'
      - 'Makefile'
      - 'base_r2s.seed'

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: luci-20.029

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
          sudo rm -rf /etc/apt/sources.list.d
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          curl https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh  | sed '/#/d' | sed 's/\\//g' | sed 's/exit 0//g' | sed 's/sudo apt -y install//g' | sed 's/sudo apt-get -y install//g' | sed 's/:i386//g' | xargs sudo apt-get -y --no-install-recommends install
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk /usr/local/share/boost /opt/ghc

      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/

      - name: Init Source
        run: |
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.1 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle --depth=1
          repo sync -c --no-tags --no-clone-bundle -j8

      - name: Mods
        run: |
          cd friendlywrt-rk3328
          sed -i '/=m/d;/CONFIG_IB/d;/CONFIG_SDK/d;/CONFIG_BUILDBOT/d;/CONFIG_ALL_KMODS/d;/CONFIG_ALL_NONSHARED/d;/docker/d;/DOCKER/d;/CONFIG_DISPLAY_SUPPORT/d;/CONFIG_AUDIO_SUPPORT/d;/CONFIG_OPENSSL_PREFER_CHACHA_OVER_GCM/d;/CONFIG_VERSION/d;/SAMBA/d;/samba/d;/modemmanager/d;' configs/config_rk3328
          sed -i '/luci-app-/d' configs/config_rk3328
          sed -i '/kmod-/d' configs/config_rk3328
          sed -i '/i18n-/d' configs/config_rk3328
          sed -i '/ppp-/d' configs/config_rk3328
          sed -i '/lib/d' configs/config_rk3328
          sed -i '/iptables/d' configs/config_rk3328
          sed -i '/firmware/d' configs/config_rk3328
          cat configs/config_rk3328 | grep "TARGET" >> ../base_r2s.seed
          cat ../base_r2s.seed > configs/config_rk3328
          cd friendlywrt
          rm -rf target/linux/rockchip-rk3328/patches-4.14/
          sed -i '5s/#src-git/src-git/g' feeds.conf.default

      - name: Add luci-theme-argon
        run: |
          mkdir -p friendlywrt-rk3328/friendlywrt/package/lean
          rm -rf friendlywrt-rk3328/friendlywrt/package/lean/luci-theme-argon
          git clone -b luci-20.029 --single-branch https://github.com/kongfl888/luci-theme-argon.git
          mv -f luci-theme-argon friendlywrt-rk3328/friendlywrt/package/lean

      - name: Build
        run: |
          cd friendlywrt-rk3328
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          wget https://raw.githubusercontent.com/kongfl888/friendlywrt_device_rk3328/master/rk3328/nanopi_r2s.mk -O .current_config.mk
          ./build.sh friendlywrt || echo ""

      - name: Assemble Artifact
        id: assemble_artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          cp friendlywrt-rk3328/friendlywrt/bin/packages/*/*/*luci-theme-argon*.ipk ./artifact/
          #cp friendlywrt-rk3328/friendlywrt/.config ./artifact/
          mkdir -p ./artifact/include/
          cp friendlywrt-rk3328/friendlywrt/rules.mk ./artifact/ || echo ""
          cp friendlywrt-rk3328/friendlywrt/include/*.mk ./artifact/include/ || echo ""
          cd ./artifact/
          sha256sum *ipk* > sha256sum.txt
          cd ..
          zip -r artifact.zip ./artifact/
          release_tag="luci-theme-argon-$(date +%Y-%m-%d-%H)"
          echo "##[set-output name=release_tag;]$release_tag"
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: Artifact
          path: ./artifact/
